//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.29 at 01:06:03 PM KST 
//


package com.tmaxsoft.xml.ns.jeus;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tmaxsoft.xml.ns.jeus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class DomainObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tmaxsoft.xml.ns.jeus
     * 
     */
    public DomainObjectFactory() {
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link Domain.Resources }
     * 
     */
    public Domain.Resources createDomainResources() {
        return new Domain.Resources();
    }

    /**
     * Create an instance of {@link Domain.Resources.DataSource }
     * 
     */
    public Domain.Resources.DataSource createDomainResourcesDataSource() {
        return new Domain.Resources.DataSource();
    }

    /**
     * Create an instance of {@link Domain.Resources.DataSource.Database }
     * 
     */
    public Domain.Resources.DataSource.Database createDomainResourcesDataSourceDatabase() {
        return new Domain.Resources.DataSource.Database();
    }

    /**
     * Create an instance of {@link Domain.Resources.DataSource.Database.ConnectionPool }
     * 
     */
    public Domain.Resources.DataSource.Database.ConnectionPool createDomainResourcesDataSourceDatabaseConnectionPool() {
        return new Domain.Resources.DataSource.Database.ConnectionPool();
    }

    /**
     * Create an instance of {@link Domain.DeployedApplications }
     * 
     */
    public Domain.DeployedApplications createDomainDeployedApplications() {
        return new Domain.DeployedApplications();
    }

    /**
     * Create an instance of {@link Domain.DeployedApplications.DeployedApplication }
     * 
     */
    public Domain.DeployedApplications.DeployedApplication createDomainDeployedApplicationsDeployedApplication() {
        return new Domain.DeployedApplications.DeployedApplication();
    }

    /**
     * Create an instance of {@link Domain.DeployedApplications.DeployedApplication.Targets }
     * 
     */
    public Domain.DeployedApplications.DeployedApplication.Targets createDomainDeployedApplicationsDeployedApplicationTargets() {
        return new Domain.DeployedApplications.DeployedApplication.Targets();
    }

    /**
     * Create an instance of {@link Domain.Servers }
     * 
     */
    public Domain.Servers createDomainServers() {
        return new Domain.Servers();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server }
     * 
     */
    public Domain.Servers.Server createDomainServersServer() {
        return new Domain.Servers.Server();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.JmsResource }
     * 
     */
    public Domain.Servers.Server.JmsResource createDomainServersServerJmsResource() {
        return new Domain.Servers.Server.JmsResource();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.LifecycleInvocation }
     * 
     */
    public Domain.Servers.Server.LifecycleInvocation createDomainServersServerLifecycleInvocation() {
        return new Domain.Servers.Server.LifecycleInvocation();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.LifecycleInvocation.Invocation }
     * 
     */
    public Domain.Servers.Server.LifecycleInvocation.Invocation createDomainServersServerLifecycleInvocationInvocation() {
        return new Domain.Servers.Server.LifecycleInvocation.Invocation();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.JmsEngine }
     * 
     */
    public Domain.Servers.Server.JmsEngine createDomainServersServerJmsEngine() {
        return new Domain.Servers.Server.JmsEngine();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.EjbEngine }
     * 
     */
    public Domain.Servers.Server.EjbEngine createDomainServersServerEjbEngine() {
        return new Domain.Servers.Server.EjbEngine();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.EjbEngine.TimerService }
     * 
     */
    public Domain.Servers.Server.EjbEngine.TimerService createDomainServersServerEjbEngineTimerService() {
        return new Domain.Servers.Server.EjbEngine.TimerService();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine }
     * 
     */
    public Domain.Servers.Server.WebEngine createDomainServersServerWebEngine() {
        return new Domain.Servers.Server.WebEngine();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.SessionConfig }
     * 
     */
    public Domain.Servers.Server.WebEngine.SessionConfig createDomainServersServerWebEngineSessionConfig() {
        return new Domain.Servers.Server.WebEngine.SessionConfig();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.AccessLog }
     * 
     */
    public Domain.Servers.Server.WebEngine.AccessLog createDomainServersServerWebEngineAccessLog() {
        return new Domain.Servers.Server.WebEngine.AccessLog();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.AccessLog.Handler }
     * 
     */
    public Domain.Servers.Server.WebEngine.AccessLog.Handler createDomainServersServerWebEngineAccessLogHandler() {
        return new Domain.Servers.Server.WebEngine.AccessLog.Handler();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.WebConnections }
     * 
     */
    public Domain.Servers.Server.WebEngine.WebConnections createDomainServersServerWebEngineWebConnections() {
        return new Domain.Servers.Server.WebEngine.WebConnections();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.WebConnections.HttpListener }
     * 
     */
    public Domain.Servers.Server.WebEngine.WebConnections.HttpListener createDomainServersServerWebEngineWebConnectionsHttpListener() {
        return new Domain.Servers.Server.WebEngine.WebConnections.HttpListener();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.SystemThreadPool }
     * 
     */
    public Domain.Servers.Server.SystemThreadPool createDomainServersServerSystemThreadPool() {
        return new Domain.Servers.Server.SystemThreadPool();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.NamingServer }
     * 
     */
    public Domain.Servers.Server.NamingServer createDomainServersServerNamingServer() {
        return new Domain.Servers.Server.NamingServer();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.NamingServer.Pooling }
     * 
     */
    public Domain.Servers.Server.NamingServer.Pooling createDomainServersServerNamingServerPooling() {
        return new Domain.Servers.Server.NamingServer.Pooling();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.TmConfig }
     * 
     */
    public Domain.Servers.Server.TmConfig createDomainServersServerTmConfig() {
        return new Domain.Servers.Server.TmConfig();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.TmConfig.Pooling }
     * 
     */
    public Domain.Servers.Server.TmConfig.Pooling createDomainServersServerTmConfigPooling() {
        return new Domain.Servers.Server.TmConfig.Pooling();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.SystemLogging }
     * 
     */
    public Domain.Servers.Server.SystemLogging createDomainServersServerSystemLogging() {
        return new Domain.Servers.Server.SystemLogging();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.SystemLogging.Handler }
     * 
     */
    public Domain.Servers.Server.SystemLogging.Handler createDomainServersServerSystemLoggingHandler() {
        return new Domain.Servers.Server.SystemLogging.Handler();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.Listeners }
     * 
     */
    public Domain.Servers.Server.Listeners createDomainServersServerListeners() {
        return new Domain.Servers.Server.Listeners();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager }
     * 
     */
    public Domain.SecurityManager createDomainSecurityManager() {
        return new Domain.SecurityManager();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains }
     * 
     */
    public Domain.SecurityManager.SecurityDomains createDomainSecurityManagerSecurityDomains() {
        return new Domain.SecurityManager.SecurityDomains();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain createDomainSecurityManagerSecurityDomainsSecurityDomain() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.CredentialVerification }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.CredentialVerification createDomainSecurityManagerSecurityDomainsSecurityDomainCredentialVerification() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.CredentialVerification();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization createDomainSecurityManagerSecurityDomainsSecurityDomainAuthorization() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService createDomainSecurityManagerSecurityDomainsSecurityDomainAuthorizationRepositoryService() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService.XmlFileRepository }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService.XmlFileRepository createDomainSecurityManagerSecurityDomainsSecurityDomainAuthorizationRepositoryServiceXmlFileRepository() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService.XmlFileRepository();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication createDomainSecurityManagerSecurityDomainsSecurityDomainAuthentication() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService createDomainSecurityManagerSecurityDomainsSecurityDomainAuthenticationRepositoryService() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService.XmlFileRepository }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService.XmlFileRepository createDomainSecurityManagerSecurityDomainsSecurityDomainAuthenticationRepositoryServiceXmlFileRepository() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService.XmlFileRepository();
    }

    /**
     * Create an instance of {@link Domain.GroupCommunicationInfo }
     * 
     */
    public Domain.GroupCommunicationInfo createDomainGroupCommunicationInfo() {
        return new Domain.GroupCommunicationInfo();
    }

    /**
     * Create an instance of {@link Domain.Gms }
     * 
     */
    public Domain.Gms createDomainGms() {
        return new Domain.Gms();
    }

    /**
     * Create an instance of {@link Domain.Resources.DataSource.Database.Property }
     * 
     */
    public Domain.Resources.DataSource.Database.Property createDomainResourcesDataSourceDatabaseProperty() {
        return new Domain.Resources.DataSource.Database.Property();
    }

    /**
     * Create an instance of {@link Domain.Resources.DataSource.Database.ConnectionPool.Pooling }
     * 
     */
    public Domain.Resources.DataSource.Database.ConnectionPool.Pooling createDomainResourcesDataSourceDatabaseConnectionPoolPooling() {
        return new Domain.Resources.DataSource.Database.ConnectionPool.Pooling();
    }

    /**
     * Create an instance of {@link Domain.Resources.DataSource.Database.ConnectionPool.WaitFreeConnection }
     * 
     */
    public Domain.Resources.DataSource.Database.ConnectionPool.WaitFreeConnection createDomainResourcesDataSourceDatabaseConnectionPoolWaitFreeConnection() {
        return new Domain.Resources.DataSource.Database.ConnectionPool.WaitFreeConnection();
    }

    /**
     * Create an instance of {@link Domain.Resources.DataSource.Database.ConnectionPool.ConnectionTrace }
     * 
     */
    public Domain.Resources.DataSource.Database.ConnectionPool.ConnectionTrace createDomainResourcesDataSourceDatabaseConnectionPoolConnectionTrace() {
        return new Domain.Resources.DataSource.Database.ConnectionPool.ConnectionTrace();
    }

    /**
     * Create an instance of {@link Domain.DeployedApplications.DeployedApplication.Options }
     * 
     */
    public Domain.DeployedApplications.DeployedApplication.Options createDomainDeployedApplicationsDeployedApplicationOptions() {
        return new Domain.DeployedApplications.DeployedApplication.Options();
    }

    /**
     * Create an instance of {@link Domain.DeployedApplications.DeployedApplication.Targets.Server }
     * 
     */
    public Domain.DeployedApplications.DeployedApplication.Targets.Server createDomainDeployedApplicationsDeployedApplicationTargetsServer() {
        return new Domain.DeployedApplications.DeployedApplication.Targets.Server();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.JvmConfig }
     * 
     */
    public Domain.Servers.Server.JvmConfig createDomainServersServerJvmConfig() {
        return new Domain.Servers.Server.JvmConfig();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.UserInterceptor }
     * 
     */
    public Domain.Servers.Server.UserInterceptor createDomainServersServerUserInterceptor() {
        return new Domain.Servers.Server.UserInterceptor();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.Gms }
     * 
     */
    public Domain.Servers.Server.Gms createDomainServersServerGms() {
        return new Domain.Servers.Server.Gms();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.DataSources }
     * 
     */
    public Domain.Servers.Server.DataSources createDomainServersServerDataSources() {
        return new Domain.Servers.Server.DataSources();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.JmsResource.Destination }
     * 
     */
    public Domain.Servers.Server.JmsResource.Destination createDomainServersServerJmsResourceDestination() {
        return new Domain.Servers.Server.JmsResource.Destination();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.LifecycleInvocation.Invocation.InvocationMethod }
     * 
     */
    public Domain.Servers.Server.LifecycleInvocation.Invocation.InvocationMethod createDomainServersServerLifecycleInvocationInvocationInvocationMethod() {
        return new Domain.Servers.Server.LifecycleInvocation.Invocation.InvocationMethod();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.JmsEngine.ServiceConfig }
     * 
     */
    public Domain.Servers.Server.JmsEngine.ServiceConfig createDomainServersServerJmsEngineServiceConfig() {
        return new Domain.Servers.Server.JmsEngine.ServiceConfig();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.JmsEngine.ThreadPool }
     * 
     */
    public Domain.Servers.Server.JmsEngine.ThreadPool createDomainServersServerJmsEngineThreadPool() {
        return new Domain.Servers.Server.JmsEngine.ThreadPool();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.JmsEngine.ConnectionFactory }
     * 
     */
    public Domain.Servers.Server.JmsEngine.ConnectionFactory createDomainServersServerJmsEngineConnectionFactory() {
        return new Domain.Servers.Server.JmsEngine.ConnectionFactory();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.EjbEngine.ActiveManagement }
     * 
     */
    public Domain.Servers.Server.EjbEngine.ActiveManagement createDomainServersServerEjbEngineActiveManagement() {
        return new Domain.Servers.Server.EjbEngine.ActiveManagement();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.EjbEngine.AsyncService }
     * 
     */
    public Domain.Servers.Server.EjbEngine.AsyncService createDomainServersServerEjbEngineAsyncService() {
        return new Domain.Servers.Server.EjbEngine.AsyncService();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.EjbEngine.TimerService.ThreadPool }
     * 
     */
    public Domain.Servers.Server.EjbEngine.TimerService.ThreadPool createDomainServersServerEjbEngineTimerServiceThreadPool() {
        return new Domain.Servers.Server.EjbEngine.TimerService.ThreadPool();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.JspEngine }
     * 
     */
    public Domain.Servers.Server.WebEngine.JspEngine createDomainServersServerWebEngineJspEngine() {
        return new Domain.Servers.Server.WebEngine.JspEngine();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.Monitoring }
     * 
     */
    public Domain.Servers.Server.WebEngine.Monitoring createDomainServersServerWebEngineMonitoring() {
        return new Domain.Servers.Server.WebEngine.Monitoring();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.BlockedUrlPatterns }
     * 
     */
    public Domain.Servers.Server.WebEngine.BlockedUrlPatterns createDomainServersServerWebEngineBlockedUrlPatterns() {
        return new Domain.Servers.Server.WebEngine.BlockedUrlPatterns();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.SessionConfig.TrackingMode }
     * 
     */
    public Domain.Servers.Server.WebEngine.SessionConfig.TrackingMode createDomainServersServerWebEngineSessionConfigTrackingMode() {
        return new Domain.Servers.Server.WebEngine.SessionConfig.TrackingMode();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.SessionConfig.SessionCookie }
     * 
     */
    public Domain.Servers.Server.WebEngine.SessionConfig.SessionCookie createDomainServersServerWebEngineSessionConfigSessionCookie() {
        return new Domain.Servers.Server.WebEngine.SessionConfig.SessionCookie();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.AccessLog.Handler.FileHandler }
     * 
     */
    public Domain.Servers.Server.WebEngine.AccessLog.Handler.FileHandler createDomainServersServerWebEngineAccessLogHandlerFileHandler() {
        return new Domain.Servers.Server.WebEngine.AccessLog.Handler.FileHandler();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.WebEngine.WebConnections.HttpListener.ThreadPool }
     * 
     */
    public Domain.Servers.Server.WebEngine.WebConnections.HttpListener.ThreadPool createDomainServersServerWebEngineWebConnectionsHttpListenerThreadPool() {
        return new Domain.Servers.Server.WebEngine.WebConnections.HttpListener.ThreadPool();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.SystemThreadPool.StuckThreadHandling }
     * 
     */
    public Domain.Servers.Server.SystemThreadPool.StuckThreadHandling createDomainServersServerSystemThreadPoolStuckThreadHandling() {
        return new Domain.Servers.Server.SystemThreadPool.StuckThreadHandling();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.NamingServer.Pooling.Shared }
     * 
     */
    public Domain.Servers.Server.NamingServer.Pooling.Shared createDomainServersServerNamingServerPoolingShared() {
        return new Domain.Servers.Server.NamingServer.Pooling.Shared();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.TmConfig.Pooling.Shared }
     * 
     */
    public Domain.Servers.Server.TmConfig.Pooling.Shared createDomainServersServerTmConfigPoolingShared() {
        return new Domain.Servers.Server.TmConfig.Pooling.Shared();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.SystemLogging.Handler.FileHandler }
     * 
     */
    public Domain.Servers.Server.SystemLogging.Handler.FileHandler createDomainServersServerSystemLoggingHandlerFileHandler() {
        return new Domain.Servers.Server.SystemLogging.Handler.FileHandler();
    }

    /**
     * Create an instance of {@link Domain.Servers.Server.Listeners.Listener }
     * 
     */
    public Domain.Servers.Server.Listeners.Listener createDomainServersServerListenersListener() {
        return new Domain.Servers.Server.Listeners.Listener();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.CredentialVerification.DefaultCredentialVerificationService }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.CredentialVerification.DefaultCredentialVerificationService createDomainSecurityManagerSecurityDomainsSecurityDomainCredentialVerificationDefaultCredentialVerificationService() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.CredentialVerification.DefaultCredentialVerificationService();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.CustomAuthorizationService }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.CustomAuthorizationService createDomainSecurityManagerSecurityDomainsSecurityDomainAuthorizationCustomAuthorizationService() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.CustomAuthorizationService();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService.XmlFileRepository.ConfigFile }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService.XmlFileRepository.ConfigFile createDomainSecurityManagerSecurityDomainsSecurityDomainAuthorizationRepositoryServiceXmlFileRepositoryConfigFile() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authorization.RepositoryService.XmlFileRepository.ConfigFile();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.CustomAuthenticationService }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.CustomAuthenticationService createDomainSecurityManagerSecurityDomainsSecurityDomainAuthenticationCustomAuthenticationService() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.CustomAuthenticationService();
    }

    /**
     * Create an instance of {@link Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService.XmlFileRepository.ConfigFile }
     * 
     */
    public Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService.XmlFileRepository.ConfigFile createDomainSecurityManagerSecurityDomainsSecurityDomainAuthenticationRepositoryServiceXmlFileRepositoryConfigFile() {
        return new Domain.SecurityManager.SecurityDomains.SecurityDomain.Authentication.RepositoryService.XmlFileRepository.ConfigFile();
    }

}
