//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 05:29:17 PM KST 
//


package com.tmaxsoft.xml.ns.jeus;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tmaxsoft.xml.ns.jeus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class NodesObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tmaxsoft.xml.ns.jeus
     * 
     */
    public NodesObjectFactory() {
    }

    /**
     * Create an instance of {@link Nodes }
     * 
     */
    public Nodes createNodes() {
        return new Nodes();
    }

    /**
     * Create an instance of {@link Nodes.Node }
     * 
     */
    public Nodes.Node createNodesNode() {
        return new Nodes.Node();
    }

    /**
     * Create an instance of {@link Nodes.Node.Java }
     * 
     */
    public Nodes.Node.Java createNodesNodeJava() {
        return new Nodes.Node.Java();
    }

}
