//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 05:29:17 PM KST 
//


package com.tmaxsoft.xml.ns.jeus;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "node"
})
@XmlRootElement(name = "nodes")
public class Nodes {

    @XmlElement(required = true)
    protected List<Nodes.Node> node;
    @XmlAttribute(name = "version")
    protected Float version;

    /**
     * Gets the value of the node property.
     * 
     * @return
     *     possible object is
     *     {@link Nodes.Node }
     *     
     */
    public List<Nodes.Node> getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nodes.Node }
     *     
     */
    public void setNode(List<Nodes.Node> value) {
        this.node = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVersion(Float value) {
        this.version = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "host",
        "java"
    })
    public static class Node {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String host;
        @XmlElement(required = true)
        protected Nodes.Node.Java java;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the host property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHost() {
            return host;
        }

        /**
         * Sets the value of the host property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHost(String value) {
            this.host = value;
        }

        /**
         * Gets the value of the java property.
         * 
         * @return
         *     possible object is
         *     {@link Nodes.Node.Java }
         *     
         */
        public Nodes.Node.Java getJava() {
            return java;
        }

        /**
         * Sets the value of the java property.
         * 
         * @param value
         *     allowed object is
         *     {@link Nodes.Node.Java }
         *     
         */
        public void setJava(Nodes.Node.Java value) {
            this.java = value;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "port",
            "useSsl"
        })
        public static class Java {

            protected int port;
            @XmlElement(name = "use-ssl", required = true)
            protected String useSsl;

            /**
             * Gets the value of the port property.
             * 
             */
            public int getPort() {
                return port;
            }

            /**
             * Sets the value of the port property.
             * 
             */
            public void setPort(int port2) {
                this.port = port2;
            }

            /**
             * Gets the value of the useSsl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUseSsl() {
                return useSsl;
            }

            /**
             * Sets the value of the useSsl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseSsl(String value) {
                this.useSsl = value;
            }

        }

    }

}
